<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Audit Trail Report - {{ $case->case_ref_no ?? 'N/A' }}</title>
    <style>
        @page {
            margin: 10mm;
            size: A4 landscape;
        }
        body {
            font-family: Arial, sans-serif;
            font-size: 9px;
            line-height: 1.3;
            margin: 0;
            padding: 0;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
            font-size: 16px;
        }
        .header p {
            margin: 3px 0;
            color: #666;
            font-size: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            table-layout: fixed;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 4px;
            text-align: left;
            font-size: 8px;
            vertical-align: top;
            word-wrap: break-word;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
            text-align: center;
        }
        /* Column width adjustments */
        th:nth-child(1), td:nth-child(1) { width: 4%; }  /* No */
        th:nth-child(2), td:nth-child(2) { width: 12%; } /* Timestamp */
        th:nth-child(3), td:nth-child(3) { width: 8%; }  /* Type */
        th:nth-child(4), td:nth-child(4) { width: 12%; } /* User */
        th:nth-child(5), td:nth-child(5) { width: 12%; } /* Action */
        th:nth-child(6), td:nth-child(6) { width: 30%; } /* Description */
        th:nth-child(7), td:nth-child(7) { width: 22%; } /* Changes */
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Audit Trail Report</h1>
        <p><strong>Case Reference:</strong> {{ $case->case_ref_no ?? 'N/A' }}</p>
        <p><strong>Generated:</strong> {{ $generated_at ?? date('Y-m-d H:i:s') }}</p>
        <p><strong>Generated By:</strong> {{ $generated_by ?? 'System' }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Timestamp</th>
                <th>Type</th>
                <th>User</th>
                <th>Action</th>
                <th>Description</th>
                <th>Changes</th>
            </tr>
        </thead>
        <tbody>
            @if(count($data) > 0)
                @foreach($data as $row)
                    <tr>
                        <td class="text-center">{{ $row['no'] }}</td>
                        <td>{{ $row['timestamp'] }}</td>
                        <td class="text-center">{{ $row['type'] }}</td>
                        <td>{{ $row['user'] }}</td>
                        <td>{{ $row['action'] }}</td>
                        <td>{{ $row['description'] }}</td>
                        <td>{{ $row['changes'] }}</td>
                    </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="7" class="text-center">No audit trail records found</td>
                </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated on {{ $generated_at ?? date('Y-m-d H:i:s') }} by {{ $generated_by ?? 'System' }}</p>
        <p>LegalCloud - Audit Trail System</p>
    </div>
</body>
</html>



