<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ledger Report - {{ $case->case_ref_no ?? 'N/A' }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            line-height: 1.3;
            margin: 15px;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 2px solid #333;
            padding-bottom: 8px;
        }
        .header h1 {
            margin: 0;
            color: #333;
            font-size: 16px;
        }
        .header p {
            margin: 3px 0;
            color: #666;
            font-size: 11px;
        }
        .info-section {
            margin-bottom: 10px;
            font-size: 10px;
        }
        .info-section strong {
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            table-layout: fixed;
            page-break-inside: auto;
        }
        th, td {
            border: 1px solid #333;
            padding: 4px;
            text-align: left;
            font-size: 8px;
            vertical-align: top;
            word-wrap: break-word;
        }
        th {
            background-color: #d8dbe0;
            font-weight: bold;
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .section-title {
            font-size: 12px;
            font-weight: bold;
            margin-top: 15px;
            margin-bottom: 8px;
            background-color: #e0e0e0;
            padding: 5px;
        }
        tfoot tr {
            background-color: #ced2d8;
            font-weight: bold;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        @media print {
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LH YEO & CO</h1>
        <p>Client Ledger Listing</p>
        <p>Generated on: {{ $generated_at }} | Generated by: {{ $generated_by }}</p>
    </div>

    <div class="info-section">
        <strong>Ref No:</strong> {{ $case->case_ref_no ?? 'N/A' }}<br>
        <strong>Client:</strong> {{ $customer->name ?? 'N/A' }}
    </div>

    @if ($type === 'ALL' || $type === 'CA')
        @if ($hasCALedgerPermission && isset($ledgers) && count($ledgers) > 0)
            <div class="section-title">Client Account Group</div>
            <table>
                <thead>
                    <tr>
                        <th style="width: 8%;">Date</th>
                        <th style="width: 10%;">Transaction ID</th>
                        <th style="width: 10%;">Voucher No</th>
                        <th style="width: 12%;">Payee</th>
                        <th style="width: 20%;">Remarks</th>
                        <th style="width: 8%;">Type</th>
                        <th style="width: 12%;">Bank</th>
                        <th style="width: 10%;">In/Credit (RM)</th>
                        <th style="width: 10%;">Out/Debit (RM)</th>
                        <th style="width: 10%;">Balance</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $total_debit = 0;
                        $total_credit = 0;
                        $total = 0;
                    @endphp
                    @foreach ($ledgers as $ledger)
                        @php
                            $sub_debit = 0;
                            $sub_credit = 0;
                            $sub_total = 0;
                        @endphp
                        <tr>
                            <td>{{ date('d-m-Y', strtotime($ledger->date)) }}</td>
                            <td>{{ $ledger->transaction_id }}</td>
                            <td>{{ $ledger->voucher_no ?? '-' }}</td>
                            <td>
                                @if(in_array($ledger->type, ['TRANSFER_IN','TRANSFER_OUT','SST_IN','SST_OUT','REIMB_IN','REIMB_OUT','REIMB_SST_IN','REIMB_SST_OUT']))
                                    -
                                @elseif(in_array($ledger->type, ['JOURNAL_IN','JOURNAL_OUT']))
                                    {{ $ledger->payee ?? '-' }}
                                @else
                                    {{ $ledger->payee_voucher ?? '-' }}
                                @endif
                            </td>
                            <td>{!! strip_tags($ledger->remark ?? '-') !!}</td>
                            <td>
                                @if (in_array($ledger->type, ['BILL_DISB','BILL_RECV']))
                                    Bill
                                @elseif(in_array($ledger->type, ['TRUST_DISB','TRUST_RECV']))
                                    Trust
                                @elseif(in_array($ledger->type, ['JOURNAL_IN','JOURNAL_OUT']))
                                    Journal
                                @elseif(in_array($ledger->type, ['TRANSFER_IN','TRANSFER_OUT']))
                                    Transfer
                                @elseif(in_array($ledger->type, ['SST_IN','SST_OUT']))
                                    SST
                                @elseif(in_array($ledger->type, ['REIMB_IN','REIMB_OUT']))
                                    Reimbursement
                                @elseif(in_array($ledger->type, ['REIMB_SST_IN','REIMB_SST_OUT']))
                                    Reimbursement SST
                                @elseif(in_array($ledger->type, ['CLOSEFILE_IN','CLOSEFILE_OUT']))
                                    Closed file
                                @elseif(in_array($ledger->type, ['ABORTFILE_IN','ABORTFILE_OUT']))
                                    Aborted file
                                @else
                                    {{ $ledger->type }}
                                @endif
                            </td>
                            <td>
                                @if($ledger->bank_name == '')
                                    -
                                @else
                                    {{ $ledger->bank_name }} ({{ $ledger->bank_account_no }})
                                @endif
                            </td>
                            <td class="text-right">
                                @if ($ledger->transaction_type == 'C')
                                    {{ number_format((float) $ledger->amount, 2, '.', ',') }}
                                    @php
                                        $total_credit += $ledger->amount;
                                        $sub_credit += $ledger->amount;
                                        $total += $ledger->amount;
                                    @endphp
                                @else
                                    -
                                @endif
                            </td>
                            <td class="text-right">
                                @if ($ledger->transaction_type == 'D')
                                    {{ number_format((float) $ledger->amount, 2, '.', ',') }}
                                    @php
                                        $total_debit += $ledger->amount;
                                        $sub_debit += $ledger->amount;
                                        $total -= $ledger->amount;
                                    @endphp
                                @else
                                    -
                                @endif
                            </td>
                            <td class="text-right">
                                @if ($total >= 0)
                                    {{ number_format((float) $total, 2, '.', ',') }}
                                @else
                                    ({{ number_format((float) ($total * -1), 2, '.', ',') }})
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="7" class="text-right"><strong>Grand Total</strong></td>
                        <td class="text-right"><strong>{{ number_format((float) $total_debit, 2, '.', ',') }}</strong></td>
                        <td class="text-right"><strong>{{ number_format((float) $total_credit, 2, '.', ',') }}</strong></td>
                        <td class="text-right">
                            <strong>
                                @if ($total_credit - $total_debit >= 0)
                                    {{ number_format((float) ($total_credit - $total_debit), 2, '.', ',') }}
                                @else
                                    ({{ number_format((float) (($total_credit - $total_debit) * -1), 2, '.', ',') }})
                                @endif
                            </strong>
                        </td>
                    </tr>
                </tfoot>
            </table>
        @endif
    @endif

    @if ($type === 'ALL' || $type === 'OA')
        @if ($hasOALedgerPermission && isset($oa_ledgers) && count($oa_ledgers) > 0)
            <div class="section-title">Office Account Group</div>
            <table>
                <thead>
                    <tr>
                        <th style="width: 8%;">Date</th>
                        <th style="width: 10%;">Transaction ID</th>
                        <th style="width: 10%;">Voucher No</th>
                        <th style="width: 12%;">Payee</th>
                        <th style="width: 20%;">Remarks</th>
                        <th style="width: 8%;">Type</th>
                        <th style="width: 12%;">Bank</th>
                        <th style="width: 10%;">In/Credit (RM)</th>
                        <th style="width: 10%;">Out/Debit (RM)</th>
                        <th style="width: 10%;">Balance</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $total_debit_oa = 0;
                        $total_credit_oa = 0;
                        $total_oa = 0;
                    @endphp
                    @foreach ($oa_ledgers as $ledger)
                        @php
                            $sub_debit = 0;
                            $sub_credit = 0;
                            $sub_total = 0;
                        @endphp
                        <tr>
                            <td>{{ date('d-m-Y', strtotime($ledger->date)) }}</td>
                            <td>{{ $ledger->transaction_id }}</td>
                            <td>{{ $ledger->voucher_no ?? '-' }}</td>
                            <td>
                                @if(in_array($ledger->type, ['TRANSFER_IN','TRANSFER_OUT','SST_IN','SST_OUT','REIMB_IN','REIMB_OUT','REIMB_SST_IN','REIMB_SST_OUT']))
                                    -
                                @elseif(in_array($ledger->type, ['JOURNAL_IN','JOURNAL_OUT']))
                                    {{ $ledger->payee ?? '-' }}
                                @else
                                    {{ $ledger->payee_voucher ?? '-' }}
                                @endif
                            </td>
                            <td>{!! strip_tags($ledger->remark ?? '-') !!}</td>
                            <td>
                                @if (in_array($ledger->type, ['BILL_DISB','BILL_RECV']))
                                    Bill
                                @elseif(in_array($ledger->type, ['TRUST_DISB','TRUST_RECV']))
                                    Trust
                                @elseif(in_array($ledger->type, ['JOURNAL_IN','JOURNAL_OUT']))
                                    Journal
                                @elseif(in_array($ledger->type, ['TRANSFER_IN','TRANSFER_OUT']))
                                    Transfer
                                @elseif(in_array($ledger->type, ['SST_IN','SST_OUT']))
                                    SST
                                @elseif(in_array($ledger->type, ['REIMB_IN','REIMB_OUT']))
                                    Reimbursement
                                @elseif(in_array($ledger->type, ['REIMB_SST_IN','REIMB_SST_OUT']))
                                    Reimbursement SST
                                @elseif(in_array($ledger->type, ['CLOSEFILE_IN','CLOSEFILE_OUT']))
                                    Closed file
                                @elseif(in_array($ledger->type, ['ABORTFILE_IN','ABORTFILE_OUT']))
                                    Aborted file
                                @else
                                    {{ $ledger->type }}
                                @endif
                            </td>
                            <td>
                                @if($ledger->bank_name == '')
                                    -
                                @else
                                    {{ $ledger->bank_name }} ({{ $ledger->bank_account_no }})
                                @endif
                            </td>
                            <td class="text-right">
                                @if ($ledger->transaction_type == 'C')
                                    {{ number_format((float) $ledger->amount, 2, '.', ',') }}
                                    @php
                                        $total_credit_oa += $ledger->amount;
                                        $sub_credit += $ledger->amount;
                                        $total_oa += $ledger->amount;
                                    @endphp
                                @else
                                    -
                                @endif
                            </td>
                            <td class="text-right">
                                @if ($ledger->transaction_type == 'D')
                                    {{ number_format((float) $ledger->amount, 2, '.', ',') }}
                                    @php
                                        $total_debit_oa += $ledger->amount;
                                        $sub_debit += $ledger->amount;
                                        $total_oa -= $ledger->amount;
                                    @endphp
                                @else
                                    -
                                @endif
                            </td>
                            <td class="text-right">
                                @if ($total_oa >= 0)
                                    {{ number_format((float) $total_oa, 2, '.', ',') }}
                                @else
                                    ({{ number_format((float) ($total_oa * -1), 2, '.', ',') }})
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="7" class="text-right"><strong>Grand Total</strong></td>
                        <td class="text-right"><strong>{{ number_format((float) $total_debit_oa, 2, '.', ',') }}</strong></td>
                        <td class="text-right"><strong>{{ number_format((float) $total_credit_oa, 2, '.', ',') }}</strong></td>
                        <td class="text-right">
                            <strong>
                                @if ($total_credit_oa - $total_debit_oa >= 0)
                                    {{ number_format((float) ($total_credit_oa - $total_debit_oa), 2, '.', ',') }}
                                @else
                                    ({{ number_format((float) (($total_credit_oa - $total_debit_oa) * -1), 2, '.', ',') }})
                                @endif
                            </strong>
                        </td>
                    </tr>
                </tfoot>
            </table>
        @endif
    @endif

    <div class="footer">
        <p>This report was generated on {{ $generated_at }} by {{ $generated_by }}</p>
        <p>LH YEO & CO - Legal Management System</p>
    </div>
</body>
</html>

